"""Deterministic, build-time RDF -> BAML type generation.

Reads an etkl:SemanticDataContract and its SKOS terminology and emits BAML
class/enum definitions. This runs BEFORE any document is compiled; the output is
committed and guarded by a sync test. No LLM, no runtime type building.
"""
from __future__ import annotations

from rdflib import Graph, Namespace, URIRef
from rdflib.namespace import RDF, SKOS

ETKL = Namespace("https://w3id.org/etkl#")
TX = Namespace("https://example.org/transplant#")

# Maps the contract's agent tag to a generated BAML class name.
_AGENT_CLASS = {
    "donor_clinical": "DonorClinical",
    "immunology": "Immunology",
    "logistics": "Logistics",
}


def _enum_name(scheme_local: str) -> str:
    # "scheme-abo" -> "AboGroup"; "scheme-organ" -> "Organ"
    base = scheme_local.replace("scheme-", "")
    name = "".join(part.capitalize() for part in base.split("-"))
    return name + "Group" if base == "abo" else name


def generate_baml(contract: Graph, terms: Graph) -> str:
    lines: list[str] = [
        "// GENERATED by iladub.bridge.generate_baml — do not hand-edit.",
        "// Source of truth: the contract ontology + SKOS terminology.",
        "",
        "class CodedConcept {",
        "  value string",
        "  source_quote string",
        "  confidence float",
        "}",
        "",
    ]

    # Enums for admissible SKOS schemes referenced by fields.
    schemes: dict[str, str] = {}  # scheme_uri -> enum name
    for field in contract.subjects(RDF.type, ETKL.Field):
        scheme = contract.value(field, ETKL.admissibleScheme)
        if scheme is not None and str(scheme) not in schemes:
            local = str(scheme).rsplit("#", 1)[-1]
            schemes[str(scheme)] = _enum_name(local)
    for scheme_uri, enum_name in sorted(schemes.items(), key=lambda kv: kv[1]):
        values = []
        for concept in terms.subjects(SKOS.inScheme, URIRef(scheme_uri)):
            labels = list(terms.objects(concept, SKOS.prefLabel))
            if not labels:
                continue
            # Deterministic: prefer the English label; else the sorted-first label.
            english = [l for l in labels if getattr(l, "language", None) == "en"]
            chosen = sorted(english or labels, key=str)[0]
            values.append(str(chosen))
        lines.append(f"enum {enum_name} {{")
        for v in sorted(set(values)):
            lines.append(f"  {v}")
        lines.append("  Other")
        lines.append("}")
        lines.append("")

    # One class per agent group; one optional CodedConcept property per field.
    by_agent: dict[str, list[str]] = {name: [] for name in _AGENT_CLASS.values()}
    for field in contract.subjects(RDF.type, ETKL.Field):
        agent = str(contract.value(field, TX.agent))
        prop = contract.value(field, ETKL.fillsProperty)
        prop_name = str(prop).rsplit("#", 1)[-1]
        cls = _AGENT_CLASS.get(agent)
        if cls:
            by_agent[cls].append(prop_name)

    for cls in _AGENT_CLASS.values():
        lines.append(f"class {cls} {{")
        for prop_name in sorted(by_agent[cls]):
            lines.append(f"  {prop_name} CodedConcept?")
        lines.append("}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def generate_context_baml(graph: Graph, contract_node: URIRef,
                          fn_name: str, class_name: str) -> str:
    """Emit a BAML class + extraction function for ONE context contract's fields.
    Deterministic, build-time; references the shared CodedConcept (generated_types.baml)."""
    props = []
    for field in graph.objects(contract_node, ETKL.hasField):
        prop = graph.value(field, ETKL.fillsProperty)
        if prop is not None:
            props.append(str(prop).rsplit("#", 1)[-1])
    props = sorted(set(props))
    field_list = ", ".join(props)

    lines = [
        "// GENERATED by iladub.bridge.generate_context_baml — do not hand-edit.",
        f"// Context contract: {contract_node}",
        "",
        f"class {class_name} {{",
    ]
    for p in props:
        lines.append(f"  {p} CodedConcept?")
    lines += [
        "}",
        "",
        f"function {fn_name}(doc: string) -> {class_name} {{",
        "  client Claude",
        '  prompt #"',
        f"    From the document below, extract ONLY these fields: {field_list}.",
        "    For each, copy the exact source phrase into source_quote and give a 0..1 confidence.",
        "    If a field is absent, omit it. Do not invent values.",
        "",
        "    Document:",
        "    ---",
        "    {{ doc }}",
        "    ---",
        "    {{ ctx.output_format }}",
        '  "#',
        "}",
    ]
    return "\n".join(lines).rstrip() + "\n"
